version: '3.8'


services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app


  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    ports:
      - 3001:3001
    volumes:
      - /app/node_modules
      - ./server:/app

