version: '3.8'

services:
  server:
    build: node/
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3001:3000
    volumes:
      - ./:/node
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: final-app

  app:
    build: app/
    container_name: app
    depends_on:
      - server

  mysql:
    image: mysql:5.7
    volumes:
      - final-app-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: final-app

volumes:
  final-app-data:
